name: Python Lint & Format

on:
  push:
    branches: [main, feature/*, release/*]
  pull_request:
    branches: [main, feature/*, release/*]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --no-interaction --no-root --with dev,test
      - name: Run black
        run: poetry run black --check .
    #   - name: Run flake8
    #     run: poetry run flake8 .
